// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx src/seed.ts',
  },
  datasource: {
    // If DIRECT_URL exists in .env, Prisma CLI uses it for migrations.
    // Otherwise, it falls back to DATABASE_URL.
    url: env('DIRECT_URL') || env('DATABASE_URL'),
  },
});
